version: "3"
services:
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: codeponder
    ports:
      - "5432:5432"
  server:
    image: server
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
  web:
    image: web
    ports:
      - "3000:3000"
  proxy:
    image: abiosoft/caddy:no-stats
    volumes:
      - /root/codeponder/Caddyfile:/etc/Caddyfile
      - /root/.caddy:/root/.caddy
      - /root/logs:/etc/logs
      - /root/goaccess/.html:/site/goaccess
    ports:
      - "80:80"
      - "443:443"
      - "7890:7890"
    depends_on:
      - web
      - server
  goaccess:
    image: allinurl/goaccess
    volumes:
      - /root/codeponder/goaccess/data/:/srv/data
      - /root/goaccess/.html:/srv/report
      - /root/logs:/srv/logs
    depends_on:
      - proxy
